apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "psm-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psm-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "psm-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "psm-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "psm-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        env:
        - name: PSM_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "psm-operator.fullname" . }}-config
              key: psm_host
        - name: PSM_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "psm-operator.fullname" . }}-config
              key: psm_port
        - name: PSM_USERNAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "psm-operator.fullname" . }}-config
              key: psm_username
        - name: PSM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "psm-operator.fullname" . }}-credentials
              key: password
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
