# Profile for Web Server Pods
# Connects to DMZ (VLAN 20) and Application Network (VLAN 21)
apiVersion: psm-operator.psm.microseglab.com/v1alpha1
kind: PsmWorkloadRegistration
metadata:
  name: web-tier-profile
  namespace: default
spec:
  psmServer:
    host: 192.168.0.58
    tenant: default
    credentialsSecretRef:
      name: psm-credentials
  podSelector:
    matchLabels:
      psm: "True"
      tier: web
  networkContext:
    macvlanInterfaces:
      # Connection to the public-facing DMZ network
      - networkAttachmentName: "macvlan-vlan20"
        psmNetworkName: "dmz-network"
        vlanId: 20
        psmNetworkRedirection: true
        psmVirtualRouter: "default"
        networkSubnet: "192.168.20.0/24"
        gatewayIp: "192.168.20.1"
      # Connection to the internal application network
      - networkAttachmentName: "macvlan-vlan21"
        psmNetworkName: "app-network"
        vlanId: 21
        psmNetworkRedirection: true
        psmVirtualRouter: "default"
        networkSubnet: "192.168.21.0/24"
        gatewayIp: "192.168.21.1"
  labelMapping:
    includeAllLabels: true
  payloadTemplate: |
    {
      "kind": null,
      "api-version": null,
      "meta": {
        "name": "{{.Pod.Name}}",
        "tenant": null,
        "namespace": null,
        "generation-id": null,
        "resource-version": null,
        "uuid": null,
        "labels": {
          {{- $first := true}}
          {{- range $key, $value := .Labels}}
          {{- if not $first}},{{end}}
          "{{$key}}": "{{$value}}"
          {{- $first = false}}
          {{- end}}
        },
        "self-link": null,
        "display-name": null
      },
      "spec": {
        "host-name": "{{.Pod.Spec.NodeName}}",
        "interfaces": [
          {{- $first := true}}
          {{- range $i, $iface := .Interfaces}}
          {{- $macvlanSpec := index $.NetworkContext.MacvlanInterfaces $i }}
          {{- if not $first}},{{end}}
          {
            "mac-address": "{{$iface.MACAddress}}",
            "micro-seg-vlan": null,
            "external-vlan": {{$macvlanSpec.VlanID}},
            "ip-addresses": ["{{$iface.IPAddress}}"],
            "network": null,
            "vni": null
          }
          {{- $first = false}}
          {{- end}}
        ],
        "migration-timeout": "3m",
        "dscInterfaces": null
      }
    }

