//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelMappingSpec) DeepCopyInto(out *LabelMappingSpec) {
	*out = *in
	if in.SpecificLabels != nil {
		in, out := &in.SpecificLabels, &out.SpecificLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LabelPrefixes != nil {
		in, out := &in.LabelPrefixes, &out.LabelPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelMappingSpec.
func (in *LabelMappingSpec) DeepCopy() *LabelMappingSpec {
	if in == nil {
		return nil
	}
	out := new(LabelMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacvlanInterfaceSpec) DeepCopyInto(out *MacvlanInterfaceSpec) {
	*out = *in
	if in.VlanID != nil {
		in, out := &in.VlanID, &out.VlanID
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacvlanInterfaceSpec.
func (in *MacvlanInterfaceSpec) DeepCopy() *MacvlanInterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(MacvlanInterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkContextSpec) DeepCopyInto(out *NetworkContextSpec) {
	*out = *in
	if in.MacvlanInterfaces != nil {
		in, out := &in.MacvlanInterfaces, &out.MacvlanInterfaces
		*out = make([]MacvlanInterfaceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkContextSpec.
func (in *NetworkContextSpec) DeepCopy() *NetworkContextSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkContextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterface) DeepCopyInto(out *NetworkInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterface.
func (in *NetworkInterface) DeepCopy() *NetworkInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PsmServerSpec) DeepCopyInto(out *PsmServerSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PsmServerSpec.
func (in *PsmServerSpec) DeepCopy() *PsmServerSpec {
	if in == nil {
		return nil
	}
	out := new(PsmServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PsmWorkloadRegistration) DeepCopyInto(out *PsmWorkloadRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PsmWorkloadRegistration.
func (in *PsmWorkloadRegistration) DeepCopy() *PsmWorkloadRegistration {
	if in == nil {
		return nil
	}
	out := new(PsmWorkloadRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PsmWorkloadRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PsmWorkloadRegistrationList) DeepCopyInto(out *PsmWorkloadRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PsmWorkloadRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PsmWorkloadRegistrationList.
func (in *PsmWorkloadRegistrationList) DeepCopy() *PsmWorkloadRegistrationList {
	if in == nil {
		return nil
	}
	out := new(PsmWorkloadRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PsmWorkloadRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PsmWorkloadRegistrationSpec) DeepCopyInto(out *PsmWorkloadRegistrationSpec) {
	*out = *in
	out.PsmServer = in.PsmServer
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	in.NetworkContext.DeepCopyInto(&out.NetworkContext)
	in.LabelMapping.DeepCopyInto(&out.LabelMapping)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PsmWorkloadRegistrationSpec.
func (in *PsmWorkloadRegistrationSpec) DeepCopy() *PsmWorkloadRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(PsmWorkloadRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PsmWorkloadRegistrationStatus) DeepCopyInto(out *PsmWorkloadRegistrationStatus) {
	*out = *in
	if in.SynchronizedPods != nil {
		in, out := &in.SynchronizedPods, &out.SynchronizedPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PsmWorkloadRegistrationStatus.
func (in *PsmWorkloadRegistrationStatus) DeepCopy() *PsmWorkloadRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(PsmWorkloadRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
